### PR TITLE
Don't get confused when re-publishing a previously-published version

### PR DESCRIPTION
**Pull request by acnodal-tc**
This is more of a "what do you think about this" PR, and less of a "ready to merge" PR. Do my analysis and fix look reasonable? I'm not sure how to demonstrate this but with a little guidance on Marin3r's test strategy I might be able to build a scenario.

The EC.Status desiredVersion and publishedVersion were getting
confused if you published one rev, then another, then re-published the
first one. You'd end up with the EC in a weird state where the desired
version and published version were different and there was a
CacheOutOfSync=True condition in the EC Status.Conditions.

The cause was that RevisionReconciler.Reconcile() assumed that the
ECR with the most recent LastPublishedAt was the one that we wanted to
publish, but we never updated that field so in this case it would be
older than the other ECR's LastPublishedAt.

This patch "touches" the desired ECR's LastPublishedAt which forces it
to be chosen by getVersionToPublish().

### CODE REVIEW

**Comment by roivaz** [comment]
Hi @acnodal-tc, the code looks pretty good and it would probably fix the problem you encountered, but I'm unsure on how the situation you describe comes to happen. I think there is a bug somewhere else because whenever the version (the version is just a hash of the envoy resources field) of the EC matches the version of the ECR that ECR is automatically published without even looking at the `LastPublishedAt`: field

https://github.com/3scale-ops/marin3r/blob/4f42569e4cccfa30c5a6a03b100a336a15986ce3/pkg/reconcilers/marin3r/envoyconfig/revisions/sort.go#L10-L40)

The unit test for this sort function is here https://github.com/3scale-ops/marin3r/blob/main/pkg/reconcilers/marin3r/envoyconfig/revisions/sort_test.go, maybe a good starting point should be making sure that this test covers the scenario you are describin, WDYT?

**Comment by acnodal-tc** [comment]
Thank you for the info, I'll dig in based on your suggestion.

**Comment by acnodal-tc** [comment]
You're correct, I was treating the symptom and not the cause. There was a subtle bug in the sort routine that only triggered when the list to be sorted had two items. I'll close this PR since it no longer makes sense and have opened https://github.com/3scale-ops/marin3r/pull/139

**Pull request closed without merging**
