### PR TITLE
Release v0.8.0

### PR DESCRIPTION
**Pull request by roivaz**
Bumps release v0.8.0, which will get added to the stable OLM channel.

/kind automation
/priority important-soon
/assign

### CODE REVIEW

**Review by raelga — APPROVED** [review]
/lgtm

**Comment by roivaz** [comment]
@raelga I have tweaked a little bit the e2e tests as they were failing at times due to race conditions, mainly because the kind cluster takes a lot of time starting up and sometimes tests were executed before all prereqs were actually installed in the cluster. Can you lgtm again?

**Pull request merged**
